version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/go/src/app:cached
    ports:
      - "1444:1444"
    working_dir: /go/src/app
    tty: yes
    depends_on:
      - db
      - kvs
    networks:
      - proxynet

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: go-echo-grapql
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: go-echo-grapql
      MYSQL_PASSWORD: go-echo-grapql
    volumes:
      - db-data:/var/lib/mysql:cached
    networks:
      - proxynet

  kvs:
    image: redis
    ports:
      - "6399:6379"
    networks:
      - proxynet

volumes:
  db-data:

networks:
  proxynet:
    name: custom_network
    external: true
    